"""
Shared data models for spot auto-trading subsystem.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone


@dataclass
class SpotSignal:
    """Trading decision generated by spot strategy engine."""
    symbol: str
    action: str  # BUY / SELL / HOLD
    price: float
    confidence: float
    reason: str
    fast_ma: float = 0.0
    slow_ma: float = 0.0
    rsi: float = 50.0
    momentum_pct: float = 0.0
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def is_actionable(self) -> bool:
        return self.action in {"BUY", "SELL"}


@dataclass
class SpotPosition:
    """Tracked spot position."""
    symbol: str
    quantity: float
    entry_price: float
    entry_time: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    peak_price: float = 0.0
    last_price: float = 0.0

    def __post_init__(self):
        if self.peak_price <= 0:
            self.peak_price = self.entry_price
        if self.last_price <= 0:
            self.last_price = self.entry_price

    def unrealized_pnl_pct(self) -> float:
        if self.entry_price <= 0:
            return 0.0
        return (self.last_price - self.entry_price) / self.entry_price * 100

    def market_value(self) -> float:
        return self.quantity * self.last_price


@dataclass
class SpotTrade:
    """Executed trade record."""
    symbol: str
    side: str  # BUY / SELL
    quantity: float
    price: float
    notional: float
    dry_run: bool
    order_id: str
    reason: str
    realized_pnl_usdt: float = 0.0
    cash_balance_after: float = 0.0
    account_value_after: float = 0.0
    cumulative_pnl_usdt: float = 0.0
    cumulative_return_pct: float = 0.0
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
