"""
Shared data models for spot auto-trading subsystem.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List


@dataclass
class DecisionContext:
    """Unified decision context for spot strategy."""

    symbol: str
    bar_open: float
    bar_high: float
    bar_low: float
    bar_close: float
    bar_volume: float
    recent_klines: List[Dict[str, Any]]
    quote_volume_24h: float

    has_position: bool = False
    entry_price: float = 0.0
    stop_price: float = 0.0
    max_price: float = 0.0
    position_qty: float = 0.0
    fees_paid: float = 0.0

    cash_balance: float = 0.0
    equity: float = 0.0
    day_start_equity: float = 0.0

    decision_timing: str = "on_close"
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def daily_drawdown_pct(self) -> float:
        if self.day_start_equity <= 0:
            return 0.0
        return (self.equity - self.day_start_equity) / self.day_start_equity * 100


@dataclass
class SpotSignal:
    """Trading decision generated by spot strategy engine."""
    symbol: str
    action: str  # BUY / SELL / HOLD
    price: float
    confidence: float
    reason: str
    reasons: List[str] = field(default_factory=list)
    fast_ma: float = 0.0
    slow_ma: float = 0.0
    rsi: float = 50.0
    atr: float = 0.0
    adx: float = 0.0
    trend_strength: float = 0.0
    stop_price: float = 0.0
    momentum_pct: float = 0.0
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def __post_init__(self):
        if not self.reasons:
            self.reasons = [self.reason] if self.reason else []
        if not self.reason and self.reasons:
            self.reason = self.reasons[0]

    def is_actionable(self) -> bool:
        return self.action in {"BUY", "SELL"}


@dataclass
class SpotPosition:
    """Tracked spot position."""
    symbol: str
    quantity: float
    entry_price: float
    entry_time: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    stop_price: float = 0.0
    max_price: float = 0.0
    peak_price: float = 0.0  # backwards-compatible alias
    last_price: float = 0.0
    fees_paid: float = 0.0
    realized_pnl: float = 0.0
    unrealized_pnl: float = 0.0

    def __post_init__(self):
        if self.max_price <= 0:
            self.max_price = self.entry_price
        if self.peak_price <= 0:
            self.peak_price = self.max_price
        if self.last_price <= 0:
            self.last_price = self.entry_price

    def unrealized_pnl_pct(self) -> float:
        if self.entry_price <= 0:
            return 0.0
        return (self.last_price - self.entry_price) / self.entry_price * 100

    def market_value(self) -> float:
        return self.quantity * self.last_price


@dataclass
class SpotTrade:
    """Executed trade record."""
    symbol: str
    side: str  # BUY / SELL
    quantity: float
    price: float
    notional: float
    dry_run: bool
    order_id: str
    reason: str
    reasons: List[str] = field(default_factory=list)
    fee_paid: float = 0.0
    slippage_bps: float = 0.0
    slippage_cost_usdt: float = 0.0
    expected_price: float = 0.0
    realized_pnl_usdt: float = 0.0
    cash_balance_after: float = 0.0
    account_value_after: float = 0.0
    cumulative_pnl_usdt: float = 0.0
    cumulative_return_pct: float = 0.0
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
